apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 6
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      schedulerName: hightower
      containers:
      - name: my-nginx
        image: nginx
        resources:
          requests:
            cpu: "500m"
            memory: "128m"
        ports:
        - containerPort: 80
